### ISSUE TITLE
refactorizar agregar-producto con servicio de calculos propio

### ISSUE THREAD

**Issue by Mannarino** [Mannarino/frontend-almacen#1]
en la carpeta del componente 'agregar-producto' se debe agregar un servicio que se encargue especificamente del calculo del precio final, 
no hacer un modulo solo del componente agregar producto porque seria una complicacion excesiva, pero si dejar su servicio en la misma carpeta. 
Antes esa funcionaldiad estaba en el servicio productos que era el que hacia request a la api, y ademas estaba en una carpeta llamada services alejada de esta carpeta agregar-productos, habai una mala gestion de estructura de codigo en eso.

Ademas el servicio en el metodo calcular precio final, no debe modificar valores del input form en su codigo como estaba hecho antes,eso esta mal, el metodo solo se debe encargar de recibir dos valores y retornarsolo un numero el cual es el calculo final.

**Comment by angular-moises-tec** [comment]
estoy de acerudo con la refactorizacion, y con que el metodo que calcule el precio final no deberia cambiar los valores de los input del formulario, solo deberia retornar un valor numerico

**Comment by angular-moises-tec** [comment]
este isuue se cierra,  se logro pasar el calculo a un nuevo servicio llamado calculations, pero no es especifico de la carpeta agregar-producto ya que tambien se usa en editar-producto, por lo cual se coloco este servicio en una carpeta llama services

**Comment by angular-moises-tec** [comment]
este isuue se cierra,  se logro pasar el calculo a un nuevo servicio llamado calculations, pero no es especifico de la carpeta agregar-producto ya que tambien se usa en editar-producto, por lo cual se coloco este servicio en una carpeta llama services
