### ISSUE TITLE
obserbar y setear para el campo PrecioFinal

### ISSUE THREAD

**Issue by angular-moises-tec** [Mannarino/frontend-almacen#3]
se tiene que hacer un servicio, o un metodo que este en el servicio calculations, que haga la logica de observar los campos pordentaje de ganancia y precio y que setee el campo preciofinal, ya que se esta repitiendo el mismo codigo en el componente editar-productos y agregar-productos

**Comment by Mannarino** [comment]
cerre el isuue, cree el servicio correspondiente para que no se repita la logica de observar los campos precio y porcentaje de gananncia y en base a eso calcular el precio final y setear ese precio final al campo precioFinal
